### ISSUE TITLE
TODO: Deprecate and retire Welcome Screen

### ISSUE THREAD

**Issue by dominichayesferen** [feren-OS/Feren-Welcome#1]
As is a goal on the Roadmap, and with the soon-to-be introduction of New Feren OS Store (will just be called 'Store' when released) once it has been developed, and the existence of the Tour and User Guide, I think Welcome Screen has had its heyday, and it's time to retire it.

That being said, Welcome Screen isn't unmaintainable or anything, it's just that better, more simpler and consistently designed alternatives are being made in Feren OS to ultimately perform the same job, and 'Tour' itself could even be considered a 'Welcome Screen' of sorts.

Welcome Screen will be missed, when the time comes, but I'm sure it'll be for the better. Once this task is done, Feren Welcome will be permanently archived on GitHub, and removed from Feren OS. 

TODO list to complete before retiring Welcome Screen:

- [ ] Move all items of Getting Started to the User Guide
- [ ] Make the User Guide accessible offline
- [ ] Make a replacement for the introduction page
- [x] Get rid of the 'Features' page (I'm sure its advertising can be done elsewhere in a less shameless manner)
- [x] Get rid of 'Online Store' (it was a 'Coming Soon' page anyway)
- [x] Get rid of 'Donate' (after seeing the legal requirements, not looking for donations just yet until a few future decisions are made)
- [x] Get rid of the 'Default Settings' page (all it did was give a button to go back to the Feren OS Desktop Layout and Theme)
- [ ] Get rid of 'Install Software' (requires New Feren OS Store to be released)
- [ ] Get rid of the 'Recommendations' page (this'll be replaced by the application recommendations in New Feren OS Store)
- [ ] Get rid of the 'System Specifications' page
- [ ] Get rid of the 'Keyboard Shortcuts' page
- [x] Get rid of the 'Customisation' page
- [x] Get rid of the 'Optional Tasks' page
- [ ] Get rid of the 'Drivers' page
- [x] Get rid of the 'Dual Booting' page (outdated info)
- [ ] Get rid of the 'Language & Input' page
- [x] Get rid of the 'Installation Preparation' page
- [x] Get rid of the 'System Requirements' page
- [ ] Get rid of the 'Updates and Extras' page
- [ ] Get rid of the 'Community' page
- [ ] Get rid of the 'Get Involved' page
- [x] Get rid of the 'Changelog' page (IDK, maybe make Store pop up on every snapshot update to greet users to the new Feren OS and give them a link or button to the changelog online)
